name = "SequenceJacobians"
uuid = "a9b836f9-bdfc-42ae-8c47-a66a622c1a62"
authors = ["Junyuan Chen <norman.chen.git@gmail.com>"]
version = "0.1.0"

[deps]
AutoregressiveModels = "c8ab78b9-851b-475e-9620-ae22bd4bbd17"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastLapackInterface = "29a986be-02c6-4525-aec4-84b980013641"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
TransformedLogDensities = "f9bc47f6-f3f8-4f3b-ab21-f8bc73906f26"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[weakdeps]
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NonlinearSystems = "deb0877a-d74a-4aeb-b6ac-c17f6fb4122e"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[extensions]
SeqJacNLoptExt = "NLopt"
SeqJacNLsolveExt = "NLsolve"
SeqJacNonlinearSystemsExt = "NonlinearSystems"
SeqJacRootsExt = "Roots"

[compat]
AdvancedMH = "0.7"
AutoregressiveModels = "0.1"
BlockArrays = "0.16"
CSV = "0.9, 0.10"
CodecZlib = "0.7"
CommonSolve = "0.2"
ComponentArrays = "0.13"
DataFrames = "1"
Distributions = "0.25"
FFTW = "1"
FastLapackInterface = "1.2"
FillArrays = "0.13"
FiniteDiff = "2"
Graphs = "1.4"
JSON3 = "1"
LogDensityProblems = "2"
LoopVectorization = "0.12.101"
MCMCChains = "5"
MacroTools = "0.5"
NLopt = "0.6"
NLsolve = "4.5"
NonlinearSystems = "0.1.1"
Requires = "1"
Roots = "1.4, 2"
SplitApplyCombine = "1.2"
StaticArraysCore = "1.4"
StatsAPI = "1.2"
StatsBase = "0.33"
StructArrays = "0.6"
Tables = "1"
TransformVariables = "0.8"
TransformedLogDensities = "1"
Tullio = "0.3.3"
julia = "1.6"

[extras]
AdvancedMH = "5b7e9947-ddc0-4b3f-9b55-0d8042f74170"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NonlinearSystems = "deb0877a-d74a-4aeb-b6ac-c17f6fb4122e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AdvancedMH", "CSV", "CodecZlib", "DataFrames", "DynamicHMC", "JSON3", "LoopVectorization", "MCMCChains", "NLopt", "NLsolve", "NonlinearSystems", "Random", "Roots", "Test"]
